CREATE DATABASE pome;
\c pome
CREATE TABLE IF NOT EXISTS profile (
id SERIAL PRIMARY KEY,
username VARCHAR,
bio VARCHAR,
location VARCHAR,
email  VARCHAR,
imageurl VARCHAR,
createdat TIMESTAMP);
CREATE TABLE IF NOT EXISTS updates (
id SERIAL PRIMARY KEY,
name VARCHAR,
post VARCHAR,
comment VARCHAR
);
CREATE DATABASE pome_test WITH TEMPLATE pome;
